### ISSUE TITLE
Code split support

### ISSUE THREAD

**Issue by kikoanis** [BerndWessels/preact-redux-isomorphic#2]
Any plans to support webpack code-split?

Great boilerplate for preact BTW!

**Comment by BerndWessels** [comment]
Hi @kikoanis 

Yes, the language files are already split out and lazy loaded like this:
```js
import intlDE from 'bundle-loader?lazy!react-intl/locale-data/de.js';
import intlEN from 'bundle-loader?lazy!react-intl/locale-data/en.js';
import intlMessagesDE from 'bundle-loader?lazy!../public/assets/translations/de.json';
import intlMessagesEN from 'bundle-loader?lazy!../public/assets/translations/en.json';
```

What else do you think would make sense to split out?

In some of my older `react` projects I used to have `react` and `react-dom` split out as `externals`. But `preact` is so small that there is no benefit.

We could add an example of lazy loaded routes maybe. Any preferences on that?

Cheers
Bernd

**Comment by kikoanis** [comment]
Thanks.

just a small example with 2-3 routes would be sufficient to show the case I guess. No preferences really

Thank you again for the repo.

**Comment by BerndWessels** [comment]
Ok, I'll do something after the Easter weekend 🐇🏄‍♂️
